### ISSUE TITLE
Can't create new world when on Linux

### ISSUE THREAD

**Issue by DarkShadow44** [Darkere/ServerConfigUpdater#3]
I tried playing the modpack "TNP Limitless-5", but creating a new world fails with the message "Server sent an invalid packet".
Removing this mod removes the crash. It works on Windows though...

Emptying the "serverconfigupdater-common.toml" file also prevents the crash.

Using serverconfigupdater-2.0

Exception:
```
[05Jun2022 17:46:01.514] [Netty Local Client IO #0/ERROR] [net.minecraft.network.Connection/]: Received class net.minecraft.network.protocol.game.ClientboundDisconnectPacket that couldn't be processed
java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientHandshakePacketListenerImpl cannot be cast to class net.minecraft.network.protocol.game.ClientGamePacketListener (net.minecraft.client.multiplayer.ClientHandshakePacketListenerImpl and net.minecraft.network.protocol.game.ClientGamePacketListener are in module minecraft@1.18.2 of loader 'TRANSFORMER' @1bb172dd)
	at net.minecraft.network.protocol.game.ClientboundDisconnectPacket.m_5797_(ClientboundDisconnectPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23530!/:?]
	at net.minecraft.network.Connection.m_129517_(Connection.java:168) ~[client-1.18.2-20220404.173914-srg.jar%23530!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:153) [client-1.18.2-20220404.173914-srg.jar%23530!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:53) [client-1.18.2-20220404.173914-srg.jar%23530!/:?]
```

Also see the bug I reported for the modpack: https://github.com/The-Nexus-Project/Limitless-5/issues/95

**Comment by Darkere** [comment]
Serverconfigupdater does not have any networking code. So this error cannot come from me. 

Another mod could have an issue with getting its config reset. But I don't have any way of figuring out which or why.
